Changed logging interface
PremiereGlobal/stim pull request #3
Opened 2019-02-05 07:41 UTC by thorix

2019-02-05 16:03 UTC, bartlettc22 requested changes

2019-02-05 16:03 UTC, bartlettc22 commented on pkg/log/logger.go
> +type Logger interface {
Add comments to exported objects? https://golang.org/doc/effective_go.html#commentary

2019-02-06 07:26 UTC, thorix commented on pkg/log/logger.go
> +type Logger interface {
Added some more notes

2019-02-06 18:10 UTC, bartlettc22 approved these changes

2019-02-06 18:11 UTC, merged