🍑 🥗 🍕 🍍Gyoza/added.helmify.feature
PremiereGlobal/stim pull request #57
Opened 2020-08-12 20:59 UTC by gyoza

my dog is cute

 🦍 🐮

2020-08-13 16:57 UTC, bartlettc22 commented
Denied because emoji

2020-08-13 18:07 UTC, lwahlmeier requested changes
It looks pretty good.  I do think before we merge we should talk about making it more "generic" and not helm specific.  It would turn the "value" field into a simple template, or maybe add another field for templating it.   Making it helm only seems like we will have to redo this for any tool we endup needing in the future.

2020-08-13 18:07 UTC, lwahlmeier commented on stimpacks/deploy/config.go
> +	var slug = defaultHelmifyPrefix
You dont need this var you can do `strings.Contains(s.Name, defaultHelmifyPrefix)`

2020-08-13 18:07 UTC, lwahlmeier commented on stimpacks/deploy/config.go
> +	for k, v := range envMap {
This can/should be simplified/optimized into one loop

2020-08-13 18:07 UTC, lwahlmeier commented on stimpacks/deploy/config.go
> +type HelmifySet struct {
This seems unused, we should remove it till/if its used.

2020-08-14 18:21 UTC, gyoza commented on stimpacks/deploy/config.go
> +type HelmifySet struct {
ya... I forgot I stopped using this. heh. Will take it out.

2020-08-14 18:22 UTC, gyoza commented on stimpacks/deploy/config.go
> +	for k, v := range envMap {
Will be changing this since the spec has kind of mutated into something better.

2020-08-14 18:22 UTC, gyoza commented on stimpacks/deploy/config.go
> +	var slug = defaultHelmifyPrefix
sweet.

2020-08-14 18:22 UTC, gyoza commented
> Denied because emoji :)

🍮🥂🍫🍱🍦🐫🦓🍖🐳🐈🍉🧀🌺🥄🍻🍩🥨🐇🥯🦎🦔🍴🐈🐗🍃🦒💨🥒

2020-08-17 16:36 UTC, IdlePhysicist commented
It looks like a handy feature. I'm only disappointed there wasn't an emoji in the branch name!

2020-08-19 20:13 UTC, closed without merging